#!/usr/bin/env sh
fd_hard_limit="$(ulimit -n -H)"
if [ "$fd_hard_limit" = "unlimited" ] ; then
  ulimit -n 4096
else
  ulimit -n "$fd_hard_limit"
fi

if ! cargo test ; then
  printf "\n"
  printf "\033[0;31mpre-push hook failed during:\033[0m\n"
  printf "\033[0;31m\tcargo test\033[0m\n"
  exit 1
fi

printf "\n"
printf "\033[0;32mpre-push hook succeeded\033[0m\n"
