DROP TABLE blacklisted_crates CASCADE;
DROP TABLE builds CASCADE;
DROP TABLE cdn_invalidation_queue CASCADE;
DROP TABLE compression_rels CASCADE;
DROP TABLE config CASCADE;
DROP TABLE crate_priorities CASCADE;
DROP TABLE crates CASCADE;
DROP TABLE database_versions CASCADE;
DROP TABLE doc_coverage CASCADE;
DROP TABLE files CASCADE;
DROP TABLE keyword_rels CASCADE;
DROP TABLE keywords CASCADE;
DROP TABLE owner_rels CASCADE;
DROP TABLE owners CASCADE;
DROP TABLE queue CASCADE;
DROP TABLE releases CASCADE;
DROP TABLE repositories CASCADE;
DROP TABLE sandbox_overrides CASCADE;
DROP TYPE feature;
DROP FUNCTION normalize_crate_name;
