FROM node:24-trixie-slim 

ENV DEBIAN_FRONTEND=noninteractive

# Install packaged dependencies
# hadolint ignore=DL3008
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
    build-essential \
    git \
    curl \
    cmake \
    gcc \
    g++ \
    pkg-config \
    libmagic-dev \
    libssl-dev \
    zlib1g-dev \
    ca-certificates \
    docker.io \
    xz-utils

# Install dependencies for chromium browser
# hadolint ignore=DL3008
RUN apt-get install -y --no-install-recommends \
  libasound2 \
  libatk1.0-0 \
  libatk-bridge2.0-0 \
  libc6 \
  libcairo2 \
  libcups2 \
  libdbus-1-3 \
  libexpat1 \
  libfontconfig1 \
  libgbm-dev \
  libgcc1 \
  libglib2.0-0 \
  libgtk-3-0 \
  libnspr4 \
  libpango-1.0-0 \
  libpangocairo-1.0-0 \
  libstdc++6 \
  libx11-6 \
  libx11-xcb1 \
  libxcb1 \
  libxcomposite1 \
  libxcursor1 \
  libxdamage1 \
  libxext6 \
  libxfixes3 \
  libxi6 \
  libxrandr2 \
  libxrender1 \
  libxss1 \
  libxtst6 \
  fonts-liberation \
  libnss3 \
  lsb-release \
  xdg-utils \
  wget

RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build

RUN mkdir out

COPY ../package.json /build/package.json

# For now, we need to use `--unsafe-perm=true` to go around an issue when npm tries
# to create a new folder. For reference:
# https://github.com/puppeteer/puppeteer/issues/375
#
# We also specify the version in case we need to update it to go around cache limitations.
RUN npm install --unsafe-perm=true --loglevel verbose --force

# Used in gui-tests/tester.js
ENV NODE_MODULE_PATH="/build/node_modules"

CMD ["node", "/build/out/gui-tests/tester.js"]
