name: Audit

on:
  push:
  pull_request:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - ".cargo/audit.toml"
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read
  issues: write
  checks: write

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: install
        run: |
          rustup override set stable
          rustup update stable
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
