name: Audit

on:
  push:
  pull_request:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - ".cargo/audit.toml"
  schedule:
    - cron: "0 0 * * *"

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
