on:
  pull_request_target:
    branches:
      - main
    types: [closed]

env:
  RUST_BACKTRACE: 1
  RUST_CACHE_KEY: rust-cache-20241114
  DOCSRS_PREFIX: ignored/cratesfyi-prefix
  DOCSRS_DATABASE_URL: postgresql://cratesfyi:password@localhost:15432
  DOCSRS_LOG: docs_rs=debug,rustwide=info
  AWS_ACCESS_KEY_ID: cratesfyi
  AWS_SECRET_ACCESS_KEY: secret_key
  S3_ENDPOINT: http://localhost:9000
  DOCSRS_INCLUDE_DEFAULT_TARGETS: false
  DOCSRS_DOCKER_IMAGE: ghcr.io/rust-lang/crates-build-env/linux-micro
  SENTRY_ENVIRONMENT: dev

permissions:
  contents: write
  pull-requests: write

jobs:
  commit-sqlx-changes:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    outputs:
      need_pr: ${{ steps.sqlx_check.outputs.need_pr }}
    steps:
      - uses: actions/checkout@v7

      - name: Ensure repository is up to date
        run: |
          git fetch origin
          git rebase origin/main

      - name: Install development tools
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c  # v4.3.0
        with:
          version: 2026.8.15
          install_args: --jobs=1 just cargo:sqlx-cli

      - name: restore build & cargo cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ env.RUST_CACHE_KEY }}

      - name: Commit sqlx changes on main branch if any
        id: sqlx_check
        run: |
          just sqlx-update
          # If there are differences in the SQLX files, then we push them on the main branch
          if [ -n "$(git status --porcelain .sqlx)" ]; then
            echo "need_pr=1" >> "$GITHUB_OUTPUT"
          else
            echo "need_pr=0" >> "$GITHUB_OUTPUT"
          fi

      - name: shut down test environment
        if: ${{ always() }}
        run: just compose-down-and-wipe

      - name: Open pull request
        if: ${{ steps.sqlx_check.outputs.need_pr == '1' }}
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: Update SQLX files
          committer: Docs.rs developers <docs.rs@users.noreply.github.com>
          author: Docs.rs developers <docs.rs@users.noreply.github.com>
          signoff: false
          delete-branch: true
          branch: update-sqlx-pr-${{ github.event.pull_request.number }}
          title: Update SQLX files
          body: |
            Following #${{ github.event.pull_request.number }} changes, here are the related SQLX files changes.
