name: Deploy Dev

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Build and upload docker image
    runs-on: ubuntu-latest
    environment: staging
    concurrency: staging
    if: github.repository_owner == 'rust-lang'
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Deploy to ECS
        uses: ./.github/actions/deploy-ecs
        with:
          aws-iam: "519825364412:role/ci--rust-lang--docs.rs--staging"
          cluster: docs-rs-staging
