---
name: Build & Deploy

on: [push, pull_request, workflow_dispatch]

jobs:
  docker:
    name: Build and upload docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: test building the dev image
        run: docker build -t docs-rs -f dockerfiles/Dockerfile .

      - name: Building the webserver image
        run: docker build -t docs-rs-web -f dockerfiles/Dockerfile --target web-server .

      - name: Upload the Docker image to ECR
        if: github.event_name == 'workflow_dispatch'
        uses: rust-lang/simpleinfra/github-actions/upload-docker-image@master
        with:
          image: docs-rs-web
          repository: docs-rs-web
          region: us-west-1
          aws_access_key_id: "${{ secrets.aws_access_key_id }}"
          aws_secret_access_key: "${{ secrets.aws_secret_access_key }}"
          redeploy_ecs_cluster: rust-ecs-prod
          redeploy_ecs_service: docs-rs-web
