---

name: Deploy
on:
  workflow_dispatch: {}

jobs:
  prod:
    name: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build -t docs-rs-web -f dockerfiles/Dockerfile --target web-server .

      - name: Upload the Docker image to ECR (production)
        uses: rust-lang/simpleinfra/github-actions/upload-docker-image@master
        with:
          image: docs-rs-web
          repository: docs-rs-web
          region: us-west-1
          aws_access_key_id: "${{ secrets.aws_access_key_id }}"
          aws_secret_access_key: "${{ secrets.aws_secret_access_key }}"
          redeploy_ecs_cluster: rust-ecs-prod
          redeploy_ecs_service: docs-rs-web
