on:
  pull_request_target:
    branches:
      - master
    types: [closed]

permissions:
  contents: read
  pull-requests: write

jobs:
  update-labels:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: S-waiting-on-deploy
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            S-waiting-on-async
            S-waiting-on-author
            S-waiting-on-crate-author
            S-waiting-on-decision
            S-waiting-on-review
