on:
  pull_request_target:
    branches:
      - master
    types: [opened, reopened, review_requested]

permissions:
  contents: read
  pull-requests: write

jobs:
  update-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: S-waiting-on-review
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: S-waiting-on-author
