on:
  pull_request_target:
    branches:
      - master
    types: [opened, reopened]

jobs:
  update-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: S-waiting-on-review
